### ISSUE TITLE
Do you have a debug for https://github.com/moozzyk/SignalRChat/blob/master/SignalRChatNode/index.ts?

### ISSUE THREAD

**Issue by forconz** [moozzyk/SignalRChat#1]
If I open the code by vs code.

and I create launch.json
`
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            // cnpm intall ts-node
            // cnpm intall typescript
            "program": "${workspaceRoot}/node_modules/ts-node/dist/_bin.js",
            "args": [
                "${workspaceRoot}/index.ts" // 入口文件
            ],
            "cwd": "${workspaceRoot}"
        }
    ]
}
`
and I install packages:
npm install @aspnet/signalr-client
npm install readline
npm install xmlhttprequest
npm install websocket

Now, debug the project, we will get 9 issues.
index.ts(4,7): error TS2304: Cannot find name 'global'.
index.ts(4,32): error TS2304: Cannot find name 'require'.
index.ts(5,7): error TS2304: Cannot find name 'global'.
index.ts(5,27): error TS2304: Cannot find name 'require'.
index.ts(7,35): error TS2304: Cannot find name 'process'.
index.ts(7,50): error TS2304: Cannot find name 'process'.
....

**Comment by forconz** [comment]
import * as readline from "readline"
I can not find readline.d.ts from source code.
I open Windows Powershell to exec command: npm install @types/readline
404 Not Found: @types/readline@latest

do you have readline.d.ts?

PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat> npm install @types/readline
npm ERR! code E404
npm ERR! 404 Not Found: @types/readline@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-12-24T18_32_52_100Z-debug.log

**Comment by forconz** [comment]
PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChatNode> tsc index.ts
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(2,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(3,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(4,50): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(7,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(8,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(9,50): error TS2304: Cannot find name 'Map'.
index.ts(20,34): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
index.ts(34,23): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

**Comment by moozzyk** [comment]
You will not be able to debug *.ts directly. Compile it first and set *.js as the target. Also, you need to target ES6. 
This repo contains accompanying code for these two blog posts:
- https://blog.3d-logic.com/2017/09/18/the-signalr-for-asp-net-core-javascript-client-part-1-web-applications/
- https://blog.3d-logic.com/2017/10/01/the-signalr-for-asp-net-core-javascript-client-part-2-outside-the-browser/ 

I encourage you to read the posts and follow the code and hopefully everything will be clear. 
I am closing the issue for now - if the above links do not answer your question feel free to reopen the issue.

**Comment by forconz** [comment]
if you install ts-node, and create launch.json file with vs code.
{
"version": "0.2.0",
"configurations": [
    {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceRoot}/node_modules/ts-node/dist/_bin.js",
        "args": [
            "${workspaceRoot}/index.ts"
        ],
        "cwd": "${workspaceRoot}"
    }
]
}

Now, you press F5, you can debug the ts code step by step.

**Comment by moozzyk** [comment]
Oh, I see - I have not tried ts-node. Were you able to make it work?

**Comment by moozzyk** [comment]
Not sure if you were able to make it work but I was able to run the code successfully with ts-node:

```
moozzyk:~/source/SignalRChat/SignalRChatNode$ node node_modules/ts-node/dist/bin.js index.ts
Enter your name: moozzyk
moozzyk
Information: WebSocket connected to ws://localhost:5000/chat?id=e4e1fcc2-cf85-4b4a-b8f8-e31e0c1a5dde
Information: Using HubProtocol 'json'.
> sdfdasf
moozzyk: sdfdasf
> asdfdsaf
moozzyk: asdfdsaf
>
```
Your `launch.json` looks fine to me. If it's still not working for you, let me know.
