### ISSUE TITLE
HttpClient.d.ts(2,32): error TS2304: Cannot find name 'Map'.

### ISSUE THREAD

**Issue by forconz** [moozzyk/SignalRChat#2]
PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat> tsc chat.ts
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(2,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(3,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(4,50): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(7,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(8,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(9,50): error TS2304: Cannot find name 'Map'.
node_modules/@types/jquery/index.d.ts(2961,63): error TS2304: Cannot find name 'Iterable'.

**Comment by moozzyk** [comment]
Try targeting es6.

**Comment by forconz** [comment]
tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "strict": true
  }
}

target = es6,

**Comment by moozzyk** [comment]
This should work. If it doesn't let me know and I can take a look but it
won't be until tomorrow.

**Comment by forconz** [comment]
I had been targeting ES6 in tsconfig.json which edited by Visual Studio Code,

PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat> npm install @aspnet/signalr-client
npm WARN signalrchat@1.0.0 No description
npm WARN signalrchat@1.0.0 No repository field.

+ @aspnet/signalr-client@1.0.0-alpha2-final
removed 2 packages and updated 7 packages in 3.401s
PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat>  tsc --target ES6 chat.ts
chat.ts(1,26): error TS2307: Cannot find module '@aspnet/signalr-client'.
chat.ts(2,20): error TS2307: Cannot find module 'jquery'.

PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat>  tsc chat.ts
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(2,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(3,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(4,50): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(7,32): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(8,36): error TS2304: Cannot find name 'Map'.
node_modules/@aspnet/signalr-client/dist/src/HttpClient.d.ts(9,50): error TS2304: Cannot find name 'Map'.

I used the --target flag in the tsc. it did not work well.

**Comment by forconz** [comment]
PS C:\Users\lenovo\Downloads\SignalRChat-master\SignalRChat-master\SignalRChat> tsc -v
Version 2.6.2

The typescirpt version is 2.6.2.

**Comment by moozzyk** [comment]
You just need to run `tsc` and not `tsc chat.ts`. When you specify a list of input files on the command line `tsconfig.json` is ignored. Passing `target` along with input files on the command line is still not enough because the compiler does will not know how to resolve modules.
